export const MAKE_SERIVE_CALL = 'MAKE_SERIVE_CALL';
export const MAKE_SERIVE_CALL_PENDING = 'MAKE_SERIVE_CALL_PENDING';
export const MAKE_SERIVE_CALL_FULFILLED = 'MAKE_SERIVE_CALL_FULFILLED';
export const MAKE_SERIVE_CALL_REJECTED = 'MAKE_SERIVE_CALL_REJECTED';

